dist: trusty
sudo: false
language: rust

cache:
  - apt: true
  - cargo: true

branches:
  only:
    - master
    - /^\d+\.\d+\.x$/

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: stable
      env: DEPLOY_API_DOC
      script:
        - cargo clean
        - cargo doc
        - rm -f target/doc/.lock
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        repo: tsukuyomi-rs/tsukuyomi-juniper
        target_branch: gh-pages
        local_dir: target/doc
        on:
          branch: master
